spring.application.name=clinicaMedica

#Configuração da base de dados H2

spring.datasource.url=jdbc:h2:mem:clinica;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.password=

#Consola H2

spring.h2.console.enabled=true
spring.h2.console.path/h2-console

#JPA / Hibernate

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format.sql=true
